services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # <-- Esto mapea tu carpeta actual al directorio /app del contenedor
    container_name: payments-middleware-app
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/payments?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - payment-net

  db:
    image: postgres:15-alpine
    container_name: payments-middleware-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payments" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - payment-net

  redis:
    image: redis:7-alpine
    container_name: payments-middleware-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - payment-net

volumes:
  postgres_data:
  redis_data:

networks:
  payment-net:
    driver: bridge
